### ISSUE TITLE
Jade has been depreciated

### ISSUE THREAD

**Issue by sfeye** [umkc-cs-451-2020-spring/semester-project-group-3#19]
It has been renamed to pug. Until jade is unistalled there will be critical vulnerabilities in the backend.
![image](https://app.gitkraken.com/api/glo/boards/5e4af72d0e8c720011038453/attachments/5e8e1f4e4c3ee30029b24bb1)

Depreciated dependency: https://www.npmjs.com/package/jade
Necessary dependency: https://www.npmjs.com/package/pug

How to uninstall jade: `npm unistall jade`
_optional_ `npm install pug --save`

**Comment by sfeye** [comment]
<img width="214" alt="Screen Shot 2020-04-08 at 2 04 30 PM" src="https://user-images.githubusercontent.com/37005498/78823180-dfd20500-79a1-11ea-824a-4d9453541b6f.png">

**Comment by lvolkmann** [comment]
Jade uninstalled and pug installed in its place.
